name: PS4 14.00 Radar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  radar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Executar Radar
        run: python radar/radar.py
